#!/bin/bash

domain=$1
org=$(echo $domain | cut -d '.' -f1)
ip=$(host $domain | grep 'has address' | awk '{print $NF}')
asn=$(curl -s "https://ipinfo.io/$ip/org" | awk '{print $1}')
curl -s "https://ipinfo.io/$asn" | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\/[0-9]{1,3}' | sort -u

#Usage
#     ./domaintocidr domain.com
